kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins
subjects:
- kind: User
  name: will-bennett@hotmail.co.uk
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
